/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreatsRouteImport } from './routes/threats'
import { Route as SocialEngineeringRouteImport } from './routes/social-engineering'
import { Route as ProtectingSystemsRouteImport } from './routes/protecting-systems'
import { Route as PersonalDataRouteImport } from './routes/personal-data'
import { Route as LegislationRouteImport } from './routes/legislation'
import { Route as IntellectualPropertyRouteImport } from './routes/intellectual-property'
import { Route as GamesRouteImport } from './routes/games'
import { Route as EnvironmentalRouteImport } from './routes/environmental'
import { Route as AiRouteImport } from './routes/ai'
import { Route as IndexRouteImport } from './routes/index'

const ThreatsRoute = ThreatsRouteImport.update({
  id: '/threats',
  path: '/threats',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialEngineeringRoute = SocialEngineeringRouteImport.update({
  id: '/social-engineering',
  path: '/social-engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectingSystemsRoute = ProtectingSystemsRouteImport.update({
  id: '/protecting-systems',
  path: '/protecting-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalDataRoute = PersonalDataRouteImport.update({
  id: '/personal-data',
  path: '/personal-data',
  getParentRoute: () => rootRouteImport,
} as any)
const LegislationRoute = LegislationRouteImport.update({
  id: '/legislation',
  path: '/legislation',
  getParentRoute: () => rootRouteImport,
} as any)
const IntellectualPropertyRoute = IntellectualPropertyRouteImport.update({
  id: '/intellectual-property',
  path: '/intellectual-property',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentalRoute = EnvironmentalRouteImport.update({
  id: '/environmental',
  path: '/environmental',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/environmental': typeof EnvironmentalRoute
  '/games': typeof GamesRoute
  '/intellectual-property': typeof IntellectualPropertyRoute
  '/legislation': typeof LegislationRoute
  '/personal-data': typeof PersonalDataRoute
  '/protecting-systems': typeof ProtectingSystemsRoute
  '/social-engineering': typeof SocialEngineeringRoute
  '/threats': typeof ThreatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/environmental': typeof EnvironmentalRoute
  '/games': typeof GamesRoute
  '/intellectual-property': typeof IntellectualPropertyRoute
  '/legislation': typeof LegislationRoute
  '/personal-data': typeof PersonalDataRoute
  '/protecting-systems': typeof ProtectingSystemsRoute
  '/social-engineering': typeof SocialEngineeringRoute
  '/threats': typeof ThreatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai': typeof AiRoute
  '/environmental': typeof EnvironmentalRoute
  '/games': typeof GamesRoute
  '/intellectual-property': typeof IntellectualPropertyRoute
  '/legislation': typeof LegislationRoute
  '/personal-data': typeof PersonalDataRoute
  '/protecting-systems': typeof ProtectingSystemsRoute
  '/social-engineering': typeof SocialEngineeringRoute
  '/threats': typeof ThreatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai'
    | '/environmental'
    | '/games'
    | '/intellectual-property'
    | '/legislation'
    | '/personal-data'
    | '/protecting-systems'
    | '/social-engineering'
    | '/threats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai'
    | '/environmental'
    | '/games'
    | '/intellectual-property'
    | '/legislation'
    | '/personal-data'
    | '/protecting-systems'
    | '/social-engineering'
    | '/threats'
  id:
    | '__root__'
    | '/'
    | '/ai'
    | '/environmental'
    | '/games'
    | '/intellectual-property'
    | '/legislation'
    | '/personal-data'
    | '/protecting-systems'
    | '/social-engineering'
    | '/threats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRoute: typeof AiRoute
  EnvironmentalRoute: typeof EnvironmentalRoute
  GamesRoute: typeof GamesRoute
  IntellectualPropertyRoute: typeof IntellectualPropertyRoute
  LegislationRoute: typeof LegislationRoute
  PersonalDataRoute: typeof PersonalDataRoute
  ProtectingSystemsRoute: typeof ProtectingSystemsRoute
  SocialEngineeringRoute: typeof SocialEngineeringRoute
  ThreatsRoute: typeof ThreatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threats': {
      id: '/threats'
      path: '/threats'
      fullPath: '/threats'
      preLoaderRoute: typeof ThreatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-engineering': {
      id: '/social-engineering'
      path: '/social-engineering'
      fullPath: '/social-engineering'
      preLoaderRoute: typeof SocialEngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protecting-systems': {
      id: '/protecting-systems'
      path: '/protecting-systems'
      fullPath: '/protecting-systems'
      preLoaderRoute: typeof ProtectingSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal-data': {
      id: '/personal-data'
      path: '/personal-data'
      fullPath: '/personal-data'
      preLoaderRoute: typeof PersonalDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legislation': {
      id: '/legislation'
      path: '/legislation'
      fullPath: '/legislation'
      preLoaderRoute: typeof LegislationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intellectual-property': {
      id: '/intellectual-property'
      path: '/intellectual-property'
      fullPath: '/intellectual-property'
      preLoaderRoute: typeof IntellectualPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environmental': {
      id: '/environmental'
      path: '/environmental'
      fullPath: '/environmental'
      preLoaderRoute: typeof EnvironmentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRoute: AiRoute,
  EnvironmentalRoute: EnvironmentalRoute,
  GamesRoute: GamesRoute,
  IntellectualPropertyRoute: IntellectualPropertyRoute,
  LegislationRoute: LegislationRoute,
  PersonalDataRoute: PersonalDataRoute,
  ProtectingSystemsRoute: ProtectingSystemsRoute,
  SocialEngineeringRoute: SocialEngineeringRoute,
  ThreatsRoute: ThreatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
