/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PersonalDataRouteImport } from './routes/personal-data'
import { Route as LegislationRouteImport } from './routes/legislation'
import { Route as GamesRouteImport } from './routes/games'
import { Route as EnvironmentalRouteImport } from './routes/environmental'
import { Route as IndexRouteImport } from './routes/index'

const PersonalDataRoute = PersonalDataRouteImport.update({
  id: '/personal-data',
  path: '/personal-data',
  getParentRoute: () => rootRouteImport,
} as any)
const LegislationRoute = LegislationRouteImport.update({
  id: '/legislation',
  path: '/legislation',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentalRoute = EnvironmentalRouteImport.update({
  id: '/environmental',
  path: '/environmental',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/environmental': typeof EnvironmentalRoute
  '/games': typeof GamesRoute
  '/legislation': typeof LegislationRoute
  '/personal-data': typeof PersonalDataRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/environmental': typeof EnvironmentalRoute
  '/games': typeof GamesRoute
  '/legislation': typeof LegislationRoute
  '/personal-data': typeof PersonalDataRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/environmental': typeof EnvironmentalRoute
  '/games': typeof GamesRoute
  '/legislation': typeof LegislationRoute
  '/personal-data': typeof PersonalDataRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/environmental'
    | '/games'
    | '/legislation'
    | '/personal-data'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/environmental' | '/games' | '/legislation' | '/personal-data'
  id:
    | '__root__'
    | '/'
    | '/environmental'
    | '/games'
    | '/legislation'
    | '/personal-data'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnvironmentalRoute: typeof EnvironmentalRoute
  GamesRoute: typeof GamesRoute
  LegislationRoute: typeof LegislationRoute
  PersonalDataRoute: typeof PersonalDataRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/personal-data': {
      id: '/personal-data'
      path: '/personal-data'
      fullPath: '/personal-data'
      preLoaderRoute: typeof PersonalDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legislation': {
      id: '/legislation'
      path: '/legislation'
      fullPath: '/legislation'
      preLoaderRoute: typeof LegislationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environmental': {
      id: '/environmental'
      path: '/environmental'
      fullPath: '/environmental'
      preLoaderRoute: typeof EnvironmentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnvironmentalRoute: EnvironmentalRoute,
  GamesRoute: GamesRoute,
  LegislationRoute: LegislationRoute,
  PersonalDataRoute: PersonalDataRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
